spring:
  application:
    name: my-ai-agent
  profiles:
    active: local
  ai:
    dashscope:
      api-key: ${ALIBABA_API_KEY:your-api-key}
      chat:
        options:
          model: qwen-turbo-latest
    ollama:
      base-url: http://localhost:11434
      chat:
        model: gemma3:1b
#    mcp:
#      client:
#        sse:
#          connections:
#            server1:
#              url: http://localhost:8127
##              timeout: 60000  # 设置超时时间为 60 秒
#        stdio:
#          servers-configuration: classpath:mcp-servers.json
#    vectorstore:
#      pgvector:
#        index-type: HNSW
#        dimensions: 1536
#        distance-type: COSINE_DISTANCE
#        max-document-batch-size: 10000 # Optional: Maximum number of documents per batch
server:
  port: 8123
  servlet:
    context-path: /api
# springdoc-openapi config
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.yam.myaiagent.controller
# knife4j config
knife4j:
  enable: true
  setting:
    language: zh_cn
# searchAPI
search-api:
  api-key: xxx
# 修改日志级别，查看 Spring AI 更多调用细节
logging:
  level:
    org.springframework.ai: DEBUG