package com.yam.myaiagent.tools;

/**
 * 功能：
 * 日期：2025/5/29 15:11
 */
import cn.hutool.core.io.FileUtil;

import com.yam.myaiagent.constant.FileConstant;
import org.springframework.ai.tool.annotation.Tool;
import org.springframework.ai.tool.annotation.ToolParam;

import java.nio.charset.StandardCharsets;

/**
 * Markdown 文件生成工具
 * 用于创建格式良好的 Markdown 文档
 */
public class MarkdownGenerationTool {

    @Tool(description = "Generate a Markdown file with given content", returnDirect = false)
    public String generateMarkdown(
            @ToolParam(description = "Name of the file to save the generated Markdown") String fileName,
            @ToolParam(description = "Content to be included in the Markdown file") String content) {
        // 确保文件名以 .md 结尾
        if (!fileName.toLowerCase().endsWith(".md")) {
            fileName += ".md";
        }

        String fileDir = FileConstant.FILE_SAVE_DIR + "/markdown";
        String filePath = fileDir + "/" + fileName;

        try {
            // 创建目录（如果不存在）
            FileUtil.mkdir(fileDir);

            // 格式化 Markdown 内容（可选）
            String formattedContent = formatMarkdownContent(content);

            // 将内容写入文件
            FileUtil.writeString(formattedContent, filePath, StandardCharsets.UTF_8);

            return "Markdown file generated successfully to: " + filePath;
        } catch (Exception e) {
            return "Error generating Markdown file: " + e.getMessage();
        }
    }

    /**
     * 格式化 Markdown 内容
     * 提供基本的 Markdown 内容增强功能
     */
    private String formatMarkdownContent(String rawContent) {
        StringBuilder formatted = new StringBuilder();

        // 添加自动生成的头部信息
        formatted.append("<!-- This document was auto-generated by MarkdownGenerationTool -->\n\n");

        // 如果内容没有标题，添加默认标题
        if (!rawContent.startsWith("#")) {
            formatted.append("# Generated Document\n\n");
        }

        // 添加内容
        formatted.append(rawContent);

        // 确保内容以空行结束
        if (!rawContent.endsWith("\n")) {
            formatted.append("\n");
        }

        // 添加自动生成的页脚
        formatted.append("\n---\n");
        formatted.append("*Auto-generated at: ").append(new java.util.Date()).append("*");

        return formatted.toString();
    }

    /**
     * 示例：生成标准文档结构
     */
    private String generateDocumentStructure(String content) {
        return String.format(
                "# Document Title\n\n" +
                        "## Introduction\n\n" +
                        "This document was auto-generated based on the provided content.\n\n" +
                        "## Content\n\n" +
                        "%s\n\n" +
                        "## Conclusion\n\n" +
                        "End of document. Generated at: %s\n",
                content,
                new java.util.Date()
        );
    }
}
